config/routes.rb
Rails.application.routes.draw do

  resources :valleys
    root "dinosaurs#index"

    resources :dinosaurs

  #  get "dinosaurs" => "dinosaurs#index"
  #  get 'dinosaurs/new' => "dinosaurs#new", as: :new_dinosaur
  #  get "dinosaurs/:id" => "dinosaurs#show", as: :dinosaur
  #  post "dinosaurs" => "dinosaurs#create"
  #  get 'dinosaurs/:id/edit' => 'dinosaurs#edit', as: :edit_dinosaur

  #  patch "dinosaurs/:id" => "dinosaurs#update"

  #  delete "dinosaurs/:id" => "dinosaurs#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dinosaur.rb
class Dinosaur < ApplicationRecord

  belongs_to :valley

    validates :name, presence: true
    validates :name, uniqueness: true

    validates :age, length: { maximum: 5 }, allow_blank: true
    validates :image_url, length: { maximum: 255 }, allow_blank: true

    def self.order_by_name
      order(:name)
    end

    def is_baby?
      age < 3
    end

end

app/models/valley.rb
class Valley < ApplicationRecord
    has_many :dinosaurs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController

  def index
    @dinosaurs = Dinosaur.all
  end

  def show
    @dinosaur = Dinosaur.find(params[:id])
  end

  def new
    @dinosaur = Dinosaur.new
  end

  def create
  #  dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)

    @dinosaur = Dinosaur.new(dinosaur_params)

    if @dinosaur.save
       redirect_to @dinosaur
    else
       render 'new'
    end
  end

  def edit
    @dinosaur = Dinosaur.find(params[:id])
  end

  def update
    @dinosaur = Dinosaur.find(params[:id])

  #  dinosaur_params = params.require(:dinosaur).permit(:name, :age, :image_url)

    if @dinosaur.update_attributes(dinosaur_params)
      redirect_to @dinosaur
    else
      render 'edit'
    end
  end

    def destroy
      @dinosaur = Dinosaur.find(params[:id])

      @dinosaur.destroy

      redirect_to dinosaurs_path
    end

private

  def dinosaur_params
    params.require(:dinosaur).permit(:name, :age, :image_url, :valley_id)
  end

end

app/controllers/valleys_controller.rb
class ValleysController < ApplicationController
  before_action :set_valley, only: [:show, :edit, :update, :destroy]

  # GET /valleys
  # GET /valleys.json
  def index
    @valleys = Valley.all
  end

  # GET /valleys/1
  # GET /valleys/1.json
  def show
  end

  # GET /valleys/new
  def new
    @valley = Valley.new
  end

  # GET /valleys/1/edit
  def edit
  end

  # POST /valleys
  # POST /valleys.json
  def create
    @valley = Valley.new(valley_params)

    respond_to do |format|
      if @valley.save
        format.html { redirect_to @valley, notice: 'Valley was successfully created.' }
        format.json { render :show, status: :created, location: @valley }
      else
        format.html { render :new }
        format.json { render json: @valley.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valleys/1
  # PATCH/PUT /valleys/1.json
  def update
    respond_to do |format|
      if @valley.update(valley_params)
        format.html { redirect_to @valley, notice: 'Valley was successfully updated.' }
        format.json { render :show, status: :ok, location: @valley }
      else
        format.html { render :edit }
        format.json { render json: @valley.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valleys/1
  # DELETE /valleys/1.json
  def destroy
    @valley.destroy
    respond_to do |format|
      format.html { redirect_to valleys_url, notice: 'Valley was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valley
      @valley = Valley.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valley_params
      params.require(:valley).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/helpers/valleys_helper.rb
module ValleysHelper
end

app/views/dinosaurs/_form.html.erb
<%= form_for @dinosaur do |f| %>

    <ul>
      <% @dinosaur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit (@dinosaur.new_record? ? "Create" : "Update") %>

<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Edit Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/index.html.erb
<h1>Dinosaurs</h1>

<% @dinosaurs.each do |dinosaur| %>
<p><%= link_to dinosaur.name, dinosaur_path(dinosaur.id) %></p>
<% end %>

<hr>

<%= link_to "[New Dinosaur]", new_dinosaur_path %>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur</h1>

<%= render "form" %>

app/views/dinosaurs/show.html.erb
<h1><%= @dinosaur.name %></h1>

<p>Age: <%= @dinosaur.age %></p>
<%= image_tag @dinosaur.image_url %>

<hr>

<%= link_to "[Edit]", edit_dinosaur_path(@dinosaur.id) %>
<%= link_to "[Delete]", dinosaur_path(@dinosaur.id), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValleysOfDinosaurs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <br><br>
    <hr>

<%= link_to "[All Dinosaurs]", root_path %>

  </body>
</html>

app/views/valleys/_form.html.erb
<%= form_with(model: valley, local: true) do |form| %>
  <% if valley.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valley.errors.count, "error") %> prohibited this valley from being saved:</h2>

      <ul>
      <% valley.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :valley_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%= f.label :valley_id %>
  <%= f.collection_select(:valley_id, Valley.all, :id, :name) %>
<% end %>

app/views/valleys/edit.html.erb
<h1>Editing Valley</h1>

<%= render 'form', valley: @valley %>

<%= link_to 'Show', @valley %> |
<%= link_to 'Back', valleys_path %>

app/views/valleys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valleys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valleys.each do |valley| %>
      <tr>
        <td><%= valley.name %></td>
        <td><%= link_to 'Show', valley %></td>
        <td><%= link_to 'Edit', edit_valley_path(valley) %></td>
        <td><%= link_to 'Destroy', valley, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valley', new_valley_path %>

app/views/valleys/new.html.erb
<h1>New Valley</h1>

<%= render 'form', valley: @valley %>

<%= link_to 'Back', valleys_path %>

app/views/valleys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @valley.name %>
</p>

<h4>List of Dinos</h4>

<% if @valley.dinosaurs.any? %>
  <ul>
    <% @valley.dinosaurs.each do |dino| %>
      <li><%= dino.name %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no dinos in this valley.</p>
<% end %>

<%= link_to 'Edit', edit_valley_path(@valley) %> |
<%= link_to 'Back', valleys_path %>